#! /bin/sh
### BEGIN INIT INFO
# Provides: ethereum
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: QtMiner
# Description: Starts and stops the QtMiner stratum enabled ethereum miner
# 
### END INIT INFO

QTMINER_DIR=/home/user/qtminer

case "$1" in
 start)
   su jfaisca -c $QTMINER_DIR/start.sh
   ;;
 stop)
   su root -c $QTMINER_DIR/stop.sh
   sleep 5
   ;;
 status)
   su jfaisca -c $QTMINER_DIR/status.sh
   ;;
 version)
   su jfaisca -c $QTMINER_DIR/version.sh
   ;;
 restart)
   su root -c $QTMINER_DIR/stop.sh
   sleep 5
   su jfaisca -c $QTMINER_DIR/start.sh
   ;;
 *)
   echo "Usage: ethereum {start|stop|status|version|restart}" >&2
   exit 3
   ;;
esac
