#! /bin/sh
### BEGIN INIT INFO
# Provides: ethereum
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Ethereum Go client
# Description: This file starts and stops Ethereum Go client with netstat
# 
### END INIT INFO

ETHGOSHPATH=/home/USER_NAME/eth-go-sh//eth-scripts

case "$1" in
 start)
   su USER_NAME -c $ETHGOSHPATH/start_go-ethereum.sh
   ;;
 stop)
   su USER_NAME -c $ETHGOSHPATH/stop_go-ethereum.sh
   sleep 2
   ;;
 status)
   su USER_NAME -c $ETHGOSHPATH/status_go-ethereum.sh
   ;;
 version)
   su USER_NAME -c $ETHGOSHPATH/versio_go-ethereum.sh
   ;;
 restart)
   su USER_NAME -c $ETHGOSHPATH/stop_go-ethereum.sh
   sleep 2
   su USER_NAME -c $ETHGOSHPATH/start_go-ethereum.sh
   ;;
 *)
   echo "Usage: ethereum {start|stop|status|version|restart}" >&2
   exit 3
   ;;
esac
