#! /bin/sh
### BEGIN INIT INFO
# Provides: ethereum
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Ethereum Go client
# Description: This file starts and stops Ethereum Go client with netstat
# 
### END INIT INFO

ETHEREUM_DIR=/home/user/eth-scripts
USER=user

case "$1" in
 start)
   su user -c $ETHEREUM_DIR/start-go_ethereum.sh
   ;;
 stop)
   su root -c $ETHEREUM_DIR/stop-go_ethereum.sh
   sleep 5
   ;;
 status)
   su user -c $ETHEREUM_DIR/status-go_ethereum.sh
   ;;
 version)
   su user -c $ETHEREUM_DIR/version-go_ethereum.sh
   ;;
 restart)
   su root -c $ETHEREUM_DIR/stop-go_ethereum.sh
   sleep 5
   su user -c $ETHEREUM_DIR/start-go_ethereum.sh
   ;;
 *)
   echo "Usage: ethereum {start|stop|status|version|restart}" >&2
   exit 3
   ;;
esac
